### ISSUE TITLE
Change the source for flutter_acrylic to pub.dev

### ISSUE THREAD

**Issue by Adrian-Samoticha** [fluttertools/sidekick#283]
flutter_acrylic is currently downloaded directly from GitHub, rather than from pub.dev:

```yaml
  flutter_acrylic:
    git:
      url: https://github.com/alexmercerind/flutter_acrylic.git
```

I assume this was done because the git repository offered features that were not yet released on pub.dev. However, as of today, the version of pub.dev is up-to-date with the repository. The source should therefore be set to pub.dev, so that breaking changes, if any were to be introduced, would not be automatically downloaded.
